const constants = {
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	REGISTER_ERROR: 'REGISTER_ERROR',
	REGISTER_PENDING: 'REGISTER_PENDING',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
};

export default constants;
