const constants = {
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	REGISTER_ERROR: 'REGISTER_ERROR',
	REGISTER_PENDING: 'REGISTER_PENDING',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	BOOKS_ERROR: 'BOOKS_ERROR',
	BOOKS_PENDING: 'BOOKS_PENDING',
	BOOKS_SUCCESS: 'BOOKS_SUCCESS',
	BOOK_EDIT_ERROR: 'BOOK_EDIT_ERROR',
	BOOK_EDIT_PENDING: 'BOOK_EDIT_PENDING',
	BOOK_EDIT_SUCCESS: 'BOOK_EDIT_SUCCESS',
	BOOK_CREATE_ERROR: 'BOOK_CREATE_ERROR',
	BOOK_CREATE_PENDING: 'BOOK_CREATE_PENDING',
	BOOK_CREATE_SUCCESS: 'BOOK_CREATE_SUCCESS',
	BOOK_DELETE_ERROR: 'BOOK_DELETE_ERROR',
	BOOK_DELETE_PENDING: 'BOOK_DELETE_PENDING',
	BOOK_DELETE_SUCCESS: 'BOOK_DELETE_SUCCESS',
};

export default constants;
